---
- name: Upgrade all dnf packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Include CLI package list
  ansible.builtin.include_vars: cli.yml

- name: Install CLI tools
  ansible.builtin.dnf:
    name: "{{ cli_packages }}"
    state: present

- name: Include GUI package list
  ansible.builtin.include_vars: gui.yml
  when: is_gui | default(false)

- name: Import Microsoft GPG key for VS Code
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: is_gui | default(false)

- name: Add VS Code repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/vscode.repo
    content: |
      [code]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      autorefresh=1
      type=rpm-md
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
  when: is_gui | default(false)

- name: Install GUI packages
  ansible.builtin.dnf:
    name: "{{ gui_packages }}"
    state: present
  when: is_gui | default(false)

- name: Remove plasma-discover-packagekit
  ansible.builtin.dnf:
    name: plasma-discover-packagekit
    state: absent
  when: is_gui | default(false)

- name: Include Flatpak package list
  ansible.builtin.include_vars: flatpak.yml
  when: is_gui | default(false)

- name: Add Flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  when: is_gui | default(false)

- name: Update all Flatpak packages
  ansible.builtin.command:
    cmd: flatpak update -y --system
  register: flatpak_update
  changed_when: '"Nothing to do" not in flatpak_update.stdout'
  when: is_gui | default(false)

- name: Install Flatpak packages
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    state: present
  when: is_gui | default(false)

- name: Install Nvidia drivers
  ansible.builtin.dnf:
    name: akmod-nvidia
    state: present
  when: is_nvidia | default(false)

- name: Add Nvidia Container Toolkit COPR repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/copr-ai-ml-nvidia-container-toolkit.repo
    content: |
      [copr:copr.fedorainfracloud.org:group_ai-ml:nvidia-container-toolkit]
      name=Copr repo for nvidia-container-toolkit owned by @ai-ml
      baseurl=https://download.copr.fedorainfracloud.org/results/@ai-ml/nvidia-container-toolkit/fedora-$releasever-$basearch/
      type=rpm-md
      skip_if_unavailable=True
      gpgcheck=1
      gpgkey=https://download.copr.fedorainfracloud.org/results/@ai-ml/nvidia-container-toolkit/pubkey.gpg
      repo_gpgcheck=0
      enabled=1
      enabled_metadata=1
  when: is_nvidia | default(false)

- name: Install Nvidia Container Toolkit
  ansible.builtin.dnf:
    name:
      - nvidia-container-toolkit
      - nvidia-container-toolkit-selinux
    state: present
  when: is_nvidia | default(false)

