---
- name: Create BBS backup script directory
  ansible.builtin.file:
    path: /usr/local/lib/bbs
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install BBS backup stop script
  ansible.builtin.template:
    src: bbs_service_stop.j2
    dest: /usr/local/lib/bbs/bbs-stop.sh
    owner: root
    group: root
    mode: "0755"

- name: Install BBS backup start script
  ansible.builtin.template:
    src: bbs_service_start.j2
    dest: /usr/local/lib/bbs/bbs-start.sh
    owner: root
    group: root
    mode: "0755"
