
---
- name: Create service configuration directory
  ansible.builtin.file:
    path: "{{ etc_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install configuration files
  ansible.builtin.copy:
    src: "{{ service_config_src }}/"
    dest: "{{ etc_dir }}/"
    owner: root
    group: root
    mode: preserve
  notify: Restart service
