---
- name: Create runtime directory
  ansible.builtin.file:
    path: "{{ var_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create additional runtime directories
  ansible.builtin.file:
    path: "{{ var_dir }}/{{ runtime_dir.path if runtime_dir is mapping else runtime_dir }}"
    state: directory
    owner: "{{ runtime_dir.get('owner', 'root') if runtime_dir is mapping else 'root' }}"
    group: "{{ runtime_dir.get('group', 'root') if runtime_dir is mapping else 'root' }}"
    mode: "0755"
  loop: "{{ runtime_directories | default([]) }}"
  loop_control:
    loop_var: runtime_dir

- name: Seed runtime directory
  ansible.builtin.synchronize:
    src: "{{ service_var_src }}/"
    dest: "{{ var_dir }}/"
    mode: push
    rsync_opts: "{{ ['-a', '--chown=root:root'] + var_excludes | map('regex_replace', '(.*)', '--exclude=\\1') | list }}
  when: runtime_copy | default(true)

- name: Fix var directory ownership
  ansible.builtin.file:
    path: "{{ var_dir }}"
    state: directory
    owner: "{{ var_owner }}"
    group: "{{ var_group | default(var_owner) }}"
    recurse: true
  when: var_owner is defined
