---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start systemd units
  ansible.builtin.systemd:
    name: "{{ unit }}"
    enabled: true
    state: "{{ 'started' if start_service else 'stopped' }}"
  loop: "{{ systemd_units }}"
  loop_control:
    loop_var: unit
