---
cli_packages:
  - tailscale
  - borgbackup
  - borgmatic
  - micro
  - uv
  - btop
  - duf
  - du-dust
  - ripgrep
  - rsync
  - rclone
  - git-lfs
  - tealdeer
  - chezmoi
  - ansible
  - python3-ansible-lint