---
flatpak_packages:
  - com.github.tchx84.Flatseal
  - com.vysp3r.ProtonPlus
  - dev.zed.Zed
  - io.github.ilya_zlobintsev.LACT
  - io.github.ungoogled_software.ungoogled_chromium
  - io.sourceforge.pysolfc.PySolFC
  - net.waterfox.waterfox